config/routes.rb
ScoreServer::Application.routes.draw do
  resources :games do
    collection do
      get 'find_by_gamer_id'
    end
  end
  
  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :score
  attr_accessible :gamer_id
  
  validates_presence_of :gamer_id
  validates_presence_of :score
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all.sort_by(&:score).reverse.slice!(0..9)
    @total_games = Game.all.length

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  def find_by_gamer_id
    @games = Game.find_all_by_gamer_id(params[:gamer_id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(:all)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="center">
	
	<h1>Welcome to the Score Server</h1>

	<h2>Our Top 10 High Scores List</h2>

<table class="center">
  <tr>
    <th>Score</th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= number_with_delimiter game.score %></td>
  </tr>
<% end %>
</table>

<br />

<h3>Total Games Played:<%= @total_games %></h3>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @game.score %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScoreServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>